version: '3.7'

services:

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 8080:8080
    expose:
      - 8080

  backend:
    restart: always
    container_name: backend
    env_file:
      - ./DB.ENV
    build: 
      context: ./fastApi
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - db
    command: ['uvicorn', 'main:app', '--host=0.0.0.0', '--port=8081']

  db:
    container_name: db
    build: ./services/database
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432

  bot:
    container_name: tgbot
    build: ./services/telegrambot
    environment:
      - YOUR_TOKEN="5821613520:AAFM7de1mQvJg1T6HiMskQe72JhS_icoBL8"
    depends_on:
      - backend
